# Generated by Django 3.2.12 on 2022-07-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_family', models.CharField(max_length=20)),
                ('num_members', models.IntegerField()),
                ('date_last_birth', models.DateTimeField(auto_now_add=True)),
                ('favorite_day_week', models.CharField(max_length=10)),
            ],
        ),
    ]
